/**
 * Seed data for Slovenija Prihodnosti - 2026 election parties and policy statements.
 * Parties from: https://sl.wikipedia.org/wiki/Liste_kandidatov_za_državnozborske_volitve_v_Sloveniji_2026
 */

export const parties = [
  { name: "Koalicija NSi, SLS in Fokusa", abbreviation: "NSi+SLS+FOKUS", slug: "nsi-sls-fokus", color: "#005DA4", leaderName: "Jernej Vrtovec", foundedYear: 2000, ideology: "Krščanska demokracija, sredina-desna", previousSeats: 8, website: "https://nsi.si", programUrl: "https://nsi.si/wp-content/uploads/2023/05/NSi-temeljni-program-web.pdf", logoUrl: "/logos/nsi-sls-fokus.svg", description: "Koalicija Nove Slovenije, Slovenske ljudske stranke in FOKUS Marka Lotriča." },
  { name: "Socialni demokrati", abbreviation: "SD", slug: "sd", color: "#E3002B", leaderName: "Matjaž Han", foundedYear: 1993, ideology: "Socialna demokracija", previousSeats: 27, website: "https://socialnidemokrati.si", programUrl: "https://socialnidemokrati.si/wp-content/uploads/2019/11/socialnidemokrati_pogledvprihodnost.pdf", logoUrl: "/logos/sd.svg", description: "Socialnodemokratska stranka." },
  { name: "Koalicija Levice in Vesne", abbreviation: "Levica+Vesna", slug: "levica-vesna", color: "#CC0000", leaderName: "Luka Mesec / Asta Vrečko", foundedYear: 2017, ideology: "Levičarska, zelena", previousSeats: 5, website: "https://levica.si", logoUrl: "/logos/levica-vesna.svg", description: "Predvolilna koalicija Levice in VESNA – zelena stranka." },
  { name: "Gibanje Svoboda", abbreviation: "GS", slug: "svoboda", color: "#0095DA", leaderName: "Robert Golob", foundedYear: 2022, ideology: "Liberalna sredina", previousSeats: 41, website: "https://gibanjesvoboda.si", programUrl: "https://gibanjesvoboda.si/", logoUrl: "/logos/svoboda.svg", description: "Gibanje Svoboda." },
  { name: "Slovenska demokratska stranka", abbreviation: "SDS", slug: "sds", color: "#003DA5", leaderName: "Janez Janša", foundedYear: 1989, ideology: "Konzervativna demokracija, desna", previousSeats: 27, website: "https://sds.si", programUrl: "https://www.sds.si/program/program-slovenske-demokratske-stranke/", logoUrl: "/logos/sds.svg", description: "Slovenska demokratska stranka." },
  { name: "Resni.ca", abbreviation: "Resni.ca", slug: "resnica", color: "#FF6600", leaderName: "Zoran Stevanović", foundedYear: 2024, ideology: "Državljansko gibanje", previousSeats: 0, website: "https://stranka-resnica.si", programUrl: "https://stranka-resnica.si/wp-content/uploads/2026/02/2026-02-memorandum-resnica.pdf", logoUrl: "/logos/resnica.svg", description: "Državljansko gibanje Resni.ca." },
  { name: "Demokrati. Anžeta Logarja", abbreviation: "D.", slug: "demokrati", color: "#0066B3", leaderName: "Anže Logar", foundedYear: 2024, ideology: "Liberalna sredina", previousSeats: 0, website: "https://demokrati.si", programUrl: "https://www.demokrati.si/wp-content/uploads/2026/02/volilni-program-stranke-demokrati-anzeta-logarja.pdf", logoUrl: "/logos/demokrati.svg", description: "Stranka Demokrati. Anžeta Logarja." },
  { name: "Prerod", abbreviation: "PVP", slug: "prerod", color: "#6B8E23", leaderName: "Vladimir Prebilič", foundedYear: 2022, ideology: "Reformna", previousSeats: 0, website: "https://prerod.si", programUrl: "https://prerod.si/wp-content/uploads/2025/10/listina.pdf", logoUrl: "/logos/prerod.svg", description: "Prerod - stranka Vladimirja Prebiliča." },
  { name: "Piratska stranka Slovenije", abbreviation: "Pirati", slug: "pirati", color: "#FF6600", leaderName: "Jasmin Feratović", foundedYear: 2012, ideology: "Piratska politika, digitalne pravice", previousSeats: 0, website: "https://piratskastranka.si", programUrl: "https://next.piratskastranka.si/s/TkTiRmMEZsJito5", logoUrl: "/logos/pirati.svg", description: "Piratska stranka Slovenije." },
];

/** Policy comparison statements by category - 150+ total */
export const policyStatements: { category: string; questions: string[] }[] = [
  {
    category: "Zunanja politika",
    questions: [
      "Podpira Izrael pri izvajanju napadov na Gazo",
      "Podpira ustanovitev države Palestine",
      "Podpira članstvo Ukrajine v NATO",
      "Podpira pošiljanje orožja Ukrajini",
      "Podpira sankcije proti Rusiji",
      "Podpira širitev EU na Zahodni Balkan",
      "Podpira vstop Srbije v EU",
      "Podpira povečanje obrambnega proračuna na 2% BDP",
      "Podpira skupno evropsko vojsko",
      "Podpira izstop iz NATO",
      "Podpira tesnejše odnose s Kitajsko",
      "Podpira mednarodno sodišče za vojni zločine (ICC)",
      "Podpira skupno evropsko zunanjo politiko",
      "Podpira pomoč državam v razvoju",
      "Podpira sprejem beguncev iz držav v vojni",
      "Podpira trgovinske pogodbe z EU",
      "Podpira nadaljnje poglabljanje EU integracije",
      "Podpira evropsko enotno vojsko",
      "Podpira nevtralnost Slovenije",
      "Podpira aktivno sodelovanje v Natu",
    ],
  },
  {
    category: "Socialna politika",
    questions: [
      "Podpira pravico do splava",
      "Podpira istospolne poroke",
      "Podpira posvojitev otrok za istospolne pare",
      "Podpira legalizacijo marihuane",
      "Podpira evtanazijo",
      "Podpira univerzalni temeljni dohodek (UTD)",
      "Podpira zvišanje minimalne plače",
      "Podpira brezplačno visokošolsko izobraževanje",
      "Podpira obvezno služenje vojaškega roka",
      "Podpira zmanjšanje socialnih transferjev",
      "Podpira zvišanje otroških dodatkov",
      "Podpira enakopravnost spolov v zakonodaji",
      "Podpira integracijo priseljencev",
      "Podpira kvote za ženske na volilnih listah",
      "Podpira pravice invalidov",
      "Podpira javno dostopne vrtce",
      "Podpira podaljšanje porodniškega dopusta",
      "Podpira regulacijo dela na podlagi pogodb",
      "Podpira omejitev nadur",
      "Podpira javno stanovanjsko politiko",
    ],
  },
  {
    category: "Gospodarstvo",
    questions: [
      "Podpira znižanje davka na dohodek pravnih oseb",
      "Podpira progresivno obdavčenje",
      "Podpira davek na nepremičnine",
      "Podpira privatizacijo državnih podjetij",
      "Podpira uvedbo enotne davčne stopnje (flat tax)",
      "Podpira subvencioniranje zelene energije",
      "Podpira jedrsko energijo",
      "Podpira gradnjo drugega bloka JEK (Krško 2)",
      "Podpira omejitev cen najemnin",
      "Podpira državno gradnjo stanovanj",
      "Podpira zmanjšanje javne porabe",
      "Podpira podporo malim in srednjim podjetjem",
      "Podpira uvoz tuje delovne sile",
      "Podpira regulacijo trga dela",
      "Podpira državne subvencije kmetijstvu",
      "Podpira prosti trg brez državnih posegov",
      "Podpira povečanje davkov za visoke dohodke",
      "Podpira davčno oprostitev za študentsko delo",
      "Podpira ukiniti davčne oaze",
      "Podpira investicije v infrastrukturo",
    ],
  },
  {
    category: "Zdravstvo",
    questions: [
      "Podpira ukinitev dopolnilnega zdravstvenega zavarovanja",
      "Podpira povečanje javnega financiranja zdravstva",
      "Podpira omejitev čakalnih dob z zakonom",
      "Podpira koncesije za zasebne zdravnike",
      "Podpira legalizacijo medicinske konoplje",
      "Podpira centralizacijo nakupov zdravil",
      "Podpira več plač za zdravnike v javnem sektorju",
      "Podpira obvezno cepljenje otrok",
      "Podpira e-health in digitalizacijo zdravstva",
      "Podpira preventivne programe",
      "Podpira dostop do zdravstva za vse",
      "Podpira zasebno zdravstveno zavarovanje",
      "Podpira ukiniti doplačila za zdravila",
      "Podpira več mest na medicini",
      "Podpira dolgotrajno oskrbo v domačem okolju",
    ],
  },
  {
    category: "Šolstvo",
    questions: [
      "Podpira brezplačne šolske obroke za vse učence",
      "Podpira posodobitev učnih načrtov",
      "Podpira zmanjšanje števila učencev v razredih",
      "Podpira obvezno poučevanje programiranja v OŠ",
      "Podpira obvezno poučevanje finančne pismenosti",
      "Podpira zvišanje plač učiteljem",
      "Podpira vključevanje otrok s posebnimi potrebami",
      "Podpira dvojezično izobraževanje",
      "Podpira brezplačne malice za vse učence",
      "Podpira prehod na digitalne učbenike",
      "Podpira ocenjevanje znanja z ocenami",
      "Podpira samostojnost šol pri izbiri programov",
      "Podpira obvezni predšolski vzgoji",
      "Podpira več mest na fakultetah",
      "Podpira šport in kulturo v šolah",
    ],
  },
  {
    category: "Okolje",
    questions: [
      "Podpira prepoved prodaje novih dizelskih/bencinskih avtomobilov do 2035",
      "Podpira ogljični davek",
      "Podpira širitev zavarovanih naravnih območij",
      "Podpira subvencije za električna vozila",
      "Podpira obnovljive vire energije",
      "Podpira jedrsko energijo kot prehodno rešitev",
      "Podpira krožno gospodarstvo",
      "Podpira prepoved plastičnih vrečk",
      "Podpira varstvo biodiverzitete",
      "Podpira zelene subvencije kmetom",
      "Podpira omejitev onesnaževanja zraka",
      "Podpira obnovo gozdov",
      "Podpira trajnostni promet",
      "Podpira ekološko davčno reformo",
      "Podpira prepoved razširjanja betonizacije",
    ],
  },
  {
    category: "Digitalizacija in transparentnost",
    questions: [
      "Podpira e-volitve (glasovanje po internetu)",
      "Podpira popolno transparentnost vladnih financ",
      "Podpira obvezno objavo premoženjskih kartic politikov",
      "Podpira prepoved anket pred volitvami (zadnjih 30 dni)",
      "Podpira potrdilo o nekaznovanosti za vse politike",
      "Podpira obvezno testiranje politikov na droge",
      "Podpira platformo za participativno demokracijo",
      "Podpira odprte podatke države",
      "Podpira e-upravo in digitalne postopke",
      "Podpira varstvo zasebnosti na internetu",
      "Podpira svobodno programsko opremo v javni upravi",
      "Podpira omejitev mandatov poslancev",
      "Podpira transparentno lobiranje",
      "Podpira javno dostopne pogodbe",
      "Podpira e-identiteto državljana",
    ],
  },
  {
    category: "Pravosodje",
    questions: [
      "Podpira strožje kazni za korupcijo",
      "Podpira hitrejše sodne postopke",
      "Podpira reformo sodnega sistema",
      "Podpira neodvisnost tožilstva",
      "Podpira specializacijo sodišč",
      "Podpira alternativne sankcije (namesto zapor)",
      "Podpira varstvo žrtev",
      "Podpira digitalizacijo pravosodja",
      "Podpira več sodnikov in prebivalca",
      "Podpira preprečevanje recidiva",
      "Podpira javnost sodnih postopkov",
      "Podpira ukiniti zastaranje kaznivih dejanj korupcije",
      "Podpira zaščito priče",
      "Podpira mediacijo namesto tožb",
      "Podpira enotno prakso sodišč",
    ],
  },
  {
    category: "Demografija in mladi",
    questions: [
      "Podpira spodbujanje rodnosti",
      "Podpira ugodnosti za mlade družine",
      "Podpira cenovno dostopna stanovanja za mlade",
      "Podpira preprečevanje bega možganov",
      "Podpira prvo zaposlitev brez davka",
      "Podpira štipendije za študente",
      "Podpira mladinske programe",
      "Podpira dostop do stanovanj za mlade",
      "Podpira otroške dodatke glede na število otrok",
      "Podpira vrtce za vse",
      "Podpira podaljšan porodniški dopust",
      "Podpira enakopravnost staršev pri skrbi",
      "Podpira zaposlovanje mladih",
      "Podpira stanovanjsko politiko za mlade",
      "Podpira izobraževanje brez bremena dolgov",
    ],
  },
  {
    category: "Varnost in obramba",
    questions: [
      "Podpira kibernetsko varnost",
      "Podpira povečanje obrambnih izdatkov",
      "Podpira civilno zaščito",
      "Podpira gasilstvo in reševanje",
      "Podpira policijsko prekvalifikacijo",
      "Podpira nadzor meja",
      "Podpira sodelovanje z Natom",
      "Podpira obveščevalne službe",
      "Podpira zaščito kritične infrastrukture",
      "Podpira pripravljenost na naravne nesreče",
      "Podpira mednarodno sodelovanje pri varnosti",
      "Podpira varstvo osebnih podatkov ob varnosti",
      "Podpira profesionalizacijo vojske",
      "Podpira rezerviste",
      "Podpira pomoč pri katastrofah",
    ],
  },
  {
    category: "Kultura in šport",
    questions: [
      "Podpira financiranje kulture",
      "Podpira športno infrastrukturo",
      "Podpira ohranjanje kulturne dediščine",
      "Podpira javno RTV",
      "Podpira neodvisnost medijev",
      "Podpira šport za vse generacije",
      "Podpira slovenski jezik v javnosti",
      "Podpira manjšinske jezike",
      "Podpira sodobno umetnost",
      "Podpira knjižnice in arhive",
      "Podpira ljudsko ustvarjalnost",
      "Podpira športne zveze",
      "Podpira filmsko industrijo",
      "Podpira glasbo in gledališče",
      "Podpira prostovoljstvo v kulturi",
    ],
  },
];

/** Stance matrix: party slug -> for each category index and question index, true/false/null.
 * Based on official party programs where available (Demokrati, NSi, Resnica, SDS, SD, etc.). */
type StanceRow = {
  orderIndex: number;
  demokrati: boolean | null;
  glas_upokojencev: boolean | null;
  nsi: boolean | null;
  pirati: boolean | null;
  prerod: boolean | null;
  resnica: boolean | null;
  sds: boolean | null;
  sd: boolean | null;
};

const stanceRows: StanceRow[] = [
  { orderIndex: 0, demokrati: null, glas_upokojencev: null, nsi: null, pirati: false, prerod: false, resnica: null, sds: true, sd: false },
  { orderIndex: 1, demokrati: true, glas_upokojencev: null, nsi: null, pirati: true, prerod: true, resnica: null, sds: false, sd: true },
  { orderIndex: 2, demokrati: true, glas_upokojencev: null, nsi: true, pirati: null, prerod: true, resnica: false, sds: true, sd: true },
  { orderIndex: 3, demokrati: true, glas_upokojencev: null, nsi: true, pirati: null, prerod: true, resnica: false, sds: true, sd: true },
  { orderIndex: 4, demokrati: true, glas_upokojencev: null, nsi: true, pirati: null, prerod: true, resnica: false, sds: true, sd: true },
  { orderIndex: 5, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 6, demokrati: true, glas_upokojencev: null, nsi: true, pirati: null, prerod: null, resnica: null, sds: true, sd: true },
  { orderIndex: 7, demokrati: true, glas_upokojencev: null, nsi: true, pirati: null, prerod: true, resnica: null, sds: true, sd: null },
  { orderIndex: 8, demokrati: true, glas_upokojencev: null, nsi: null, pirati: null, prerod: true, resnica: false, sds: null, sd: true },
  { orderIndex: 9, demokrati: false, glas_upokojencev: false, nsi: false, pirati: null, prerod: false, resnica: true, sds: false, sd: false },
  { orderIndex: 10, demokrati: null, glas_upokojencev: null, nsi: null, pirati: null, prerod: null, resnica: true, sds: null, sd: null },
  { orderIndex: 11, demokrati: true, glas_upokojencev: null, nsi: null, pirati: true, prerod: true, resnica: null, sds: null, sd: true },
  { orderIndex: 12, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: false, sds: true, sd: true },
  { orderIndex: 13, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 14, demokrati: null, glas_upokojencev: false, nsi: null, pirati: true, prerod: true, resnica: false, sds: false, sd: true },
  { orderIndex: 15, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 16, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: false, sds: true, sd: true },
  { orderIndex: 17, demokrati: true, glas_upokojencev: null, nsi: null, pirati: null, prerod: true, resnica: false, sds: null, sd: true },
  { orderIndex: 18, demokrati: false, glas_upokojencev: null, nsi: false, pirati: null, prerod: false, resnica: true, sds: false, sd: false },
  { orderIndex: 19, demokrati: true, glas_upokojencev: true, nsi: true, pirati: null, prerod: true, resnica: false, sds: true, sd: true },
  { orderIndex: 20, demokrati: null, glas_upokojencev: null, nsi: false, pirati: true, prerod: true, resnica: null, sds: null, sd: true },
  { orderIndex: 21, demokrati: null, glas_upokojencev: false, nsi: false, pirati: true, prerod: true, resnica: false, sds: false, sd: true },
  { orderIndex: 22, demokrati: null, glas_upokojencev: false, nsi: false, pirati: true, prerod: true, resnica: false, sds: false, sd: true },
  { orderIndex: 23, demokrati: null, glas_upokojencev: null, nsi: false, pirati: true, prerod: null, resnica: true, sds: false, sd: null },
  { orderIndex: 24, demokrati: null, glas_upokojencev: null, nsi: false, pirati: true, prerod: null, resnica: null, sds: false, sd: null },
  { orderIndex: 25, demokrati: false, glas_upokojencev: null, nsi: false, pirati: true, prerod: null, resnica: null, sds: false, sd: null },
  { orderIndex: 26, demokrati: null, glas_upokojencev: true, nsi: null, pirati: true, prerod: true, resnica: false, sds: null, sd: true },
  { orderIndex: 27, demokrati: true, glas_upokojencev: null, nsi: null, pirati: true, prerod: true, resnica: null, sds: null, sd: true },
  { orderIndex: 28, demokrati: true, glas_upokojencev: null, nsi: true, pirati: false, prerod: null, resnica: null, sds: true, sd: false },
  { orderIndex: 29, demokrati: null, glas_upokojencev: false, nsi: null, pirati: false, prerod: false, resnica: null, sds: null, sd: false },
  { orderIndex: 30, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 31, demokrati: true, glas_upokojencev: null, nsi: null, pirati: true, prerod: true, resnica: null, sds: null, sd: true },
  { orderIndex: 32, demokrati: null, glas_upokojencev: false, nsi: null, pirati: true, prerod: true, resnica: false, sds: false, sd: true },
  { orderIndex: 33, demokrati: null, glas_upokojencev: null, nsi: null, pirati: null, prerod: true, resnica: null, sds: null, sd: true },
  { orderIndex: 34, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 35, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 36, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 37, demokrati: true, glas_upokojencev: null, nsi: null, pirati: true, prerod: true, resnica: null, sds: null, sd: true },
  { orderIndex: 38, demokrati: null, glas_upokojencev: null, nsi: null, pirati: true, prerod: true, resnica: null, sds: null, sd: true },
  { orderIndex: 39, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: null, sd: true },
  { orderIndex: 40, demokrati: true, glas_upokojencev: null, nsi: true, pirati: null, prerod: null, resnica: true, sds: true, sd: false },
  { orderIndex: 41, demokrati: false, glas_upokojencev: null, nsi: null, pirati: null, prerod: true, resnica: false, sds: false, sd: true },
  { orderIndex: 42, demokrati: null, glas_upokojencev: false, nsi: null, pirati: true, prerod: null, resnica: false, sds: false, sd: null },
  { orderIndex: 43, demokrati: null, glas_upokojencev: null, nsi: true, pirati: null, prerod: false, resnica: null, sds: true, sd: false },
  { orderIndex: 44, demokrati: null, glas_upokojencev: null, nsi: null, pirati: null, prerod: false, resnica: true, sds: null, sd: false },
  { orderIndex: 45, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 46, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: null },
  { orderIndex: 47, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: null },
  { orderIndex: 48, demokrati: null, glas_upokojencev: true, nsi: null, pirati: true, prerod: true, resnica: null, sds: false, sd: true },
  { orderIndex: 49, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: null, sd: true },
  { orderIndex: 50, demokrati: true, glas_upokojencev: null, nsi: true, pirati: null, prerod: false, resnica: true, sds: true, sd: false },
  { orderIndex: 51, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 52, demokrati: true, glas_upokojencev: false, nsi: null, pirati: null, prerod: null, resnica: false, sds: false, sd: null },
  { orderIndex: 53, demokrati: true, glas_upokojencev: null, nsi: null, pirati: true, prerod: true, resnica: false, sds: null, sd: true },
  { orderIndex: 54, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 55, demokrati: null, glas_upokojencev: null, nsi: true, pirati: null, prerod: false, resnica: true, sds: true, sd: false },
  { orderIndex: 56, demokrati: false, glas_upokojencev: null, nsi: null, pirati: null, prerod: true, resnica: false, sds: false, sd: true },
  { orderIndex: 57, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 58, demokrati: null, glas_upokojencev: null, nsi: null, pirati: true, prerod: true, resnica: null, sds: null, sd: true },
  { orderIndex: 59, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 60, demokrati: true, glas_upokojencev: true, nsi: null, pirati: true, prerod: true, resnica: true, sds: null, sd: true },
  { orderIndex: 61, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 62, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 63, demokrati: true, glas_upokojencev: null, nsi: true, pirati: null, prerod: null, resnica: true, sds: true, sd: false },
  { orderIndex: 64, demokrati: null, glas_upokojencev: null, nsi: false, pirati: true, prerod: null, resnica: true, sds: null, sd: null },
  { orderIndex: 65, demokrati: null, glas_upokojencev: null, nsi: null, pirati: true, prerod: true, resnica: null, sds: null, sd: true },
  { orderIndex: 66, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 67, demokrati: null, glas_upokojencev: null, nsi: true, pirati: null, prerod: null, resnica: false, sds: null, sd: null },
  { orderIndex: 68, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 69, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 70, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 71, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 72, demokrati: true, glas_upokojencev: null, nsi: true, pirati: null, prerod: null, resnica: true, sds: true, sd: false },
  { orderIndex: 73, demokrati: null, glas_upokojencev: true, nsi: null, pirati: true, prerod: true, resnica: null, sds: null, sd: true },
  { orderIndex: 74, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 75, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 76, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 77, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 78, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 79, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 80, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 81, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 82, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 83, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 84, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 85, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 86, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 87, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 88, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 89, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 90, demokrati: false, glas_upokojencev: null, nsi: false, pirati: true, prerod: false, resnica: false, sds: false, sd: null },
  { orderIndex: 91, demokrati: null, glas_upokojencev: null, nsi: null, pirati: true, prerod: true, resnica: false, sds: null, sd: true },
  { orderIndex: 92, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 93, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 94, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 95, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: null },
  { orderIndex: 96, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 97, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 98, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 99, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 100, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 101, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 102, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 103, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 104, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 105, demokrati: true, glas_upokojencev: null, nsi: null, pirati: true, prerod: null, resnica: true, sds: null, sd: null },
  { orderIndex: 106, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 107, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 108, demokrati: null, glas_upokojencev: null, nsi: null, pirati: false, prerod: null, resnica: true, sds: null, sd: null },
  { orderIndex: 109, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 110, demokrati: null, glas_upokojencev: null, nsi: null, pirati: true, prerod: null, resnica: true, sds: null, sd: null },
  { orderIndex: 111, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 112, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 113, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 114, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 115, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 116, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 117, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 118, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 119, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 120, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 121, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 122, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 123, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 124, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 125, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 126, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 127, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 128, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 129, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 130, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 131, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 132, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 133, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 134, demokrati: true, glas_upokojencev: null, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 135, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 136, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 137, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 138, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 139, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 140, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 141, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 142, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 143, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 144, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 145, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 146, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 147, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 148, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 149, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 150, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 151, demokrati: true, glas_upokojencev: null, nsi: true, pirati: null, prerod: true, resnica: null, sds: true, sd: null },
  { orderIndex: 152, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 153, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 154, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 155, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 156, demokrati: true, glas_upokojencev: true, nsi: true, pirati: null, prerod: true, resnica: false, sds: true, sd: true },
  { orderIndex: 157, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 158, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 159, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 160, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 161, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 162, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 163, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 164, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: true, sds: true, sd: true },
  { orderIndex: 165, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 166, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 167, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 168, demokrati: true, glas_upokojencev: null, nsi: null, pirati: true, prerod: true, resnica: false, sds: false, sd: true },
  { orderIndex: 169, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 170, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 171, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 172, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 173, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 174, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 175, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 176, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 177, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 178, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
  { orderIndex: 179, demokrati: true, glas_upokojencev: true, nsi: true, pirati: true, prerod: true, resnica: null, sds: true, sd: true },
];

const stanceMap: Record<string, Record<number, boolean | null>> = {
  demokrati: {},
  "glas-upokojencev": {},
  "nsi-sls-fokus": {},
  pirati: {},
  prerod: {},
  resnica: {},
  sds: {},
  sd: {},
  svoboda: {},
  "levica-vesna": {},
};

for (const row of stanceRows) {
  stanceMap.demokrati[row.orderIndex] = row.demokrati;
  stanceMap["glas-upokojencev"][row.orderIndex] = row.glas_upokojencev;
  stanceMap["nsi-sls-fokus"][row.orderIndex] = row.nsi;
  stanceMap.pirati[row.orderIndex] = row.pirati;
  stanceMap.prerod[row.orderIndex] = row.prerod;
  stanceMap.resnica[row.orderIndex] = row.resnica;
  stanceMap.sds[row.orderIndex] = row.sds;
  stanceMap.sd[row.orderIndex] = row.sd;
}

const svobodaLevicaOverrides: { orderIndex: number; svoboda: boolean | null; levica: boolean | null }[] = [
  { orderIndex: 0, svoboda: false, levica: false },
  { orderIndex: 1, svoboda: true, levica: true },
  { orderIndex: 2, svoboda: true, levica: false },
  { orderIndex: 3, svoboda: true, levica: false },
  { orderIndex: 4, svoboda: true, levica: true },
  { orderIndex: 5, svoboda: true, levica: true },
  { orderIndex: 6, svoboda: true, levica: true },
  { orderIndex: 7, svoboda: null, levica: false },
  { orderIndex: 8, svoboda: true, levica: false },
  { orderIndex: 9, svoboda: false, levica: true },
  { orderIndex: 10, svoboda: null, levica: null },
  { orderIndex: 11, svoboda: true, levica: true },
  { orderIndex: 12, svoboda: true, levica: true },
  { orderIndex: 13, svoboda: true, levica: true },
  { orderIndex: 14, svoboda: true, levica: true },
  { orderIndex: 15, svoboda: true, levica: true },
  { orderIndex: 16, svoboda: true, levica: true },
  { orderIndex: 17, svoboda: true, levica: false },
  { orderIndex: 18, svoboda: false, levica: true },
  { orderIndex: 19, svoboda: true, levica: false },
  { orderIndex: 20, svoboda: true, levica: true },
  { orderIndex: 21, svoboda: true, levica: true },
  { orderIndex: 22, svoboda: true, levica: true },
  { orderIndex: 23, svoboda: null, levica: true },
  { orderIndex: 24, svoboda: null, levica: true },
  { orderIndex: 25, svoboda: true, levica: true },
  { orderIndex: 26, svoboda: true, levica: true },
  { orderIndex: 27, svoboda: true, levica: true },
  { orderIndex: 28, svoboda: false, levica: false },
  { orderIndex: 29, svoboda: false, levica: false },
  { orderIndex: 30, svoboda: true, levica: true },
  { orderIndex: 31, svoboda: true, levica: true },
  { orderIndex: 32, svoboda: true, levica: true },
  { orderIndex: 33, svoboda: true, levica: true },
  { orderIndex: 34, svoboda: true, levica: true },
  { orderIndex: 35, svoboda: true, levica: true },
  { orderIndex: 36, svoboda: true, levica: true },
  { orderIndex: 37, svoboda: true, levica: true },
  { orderIndex: 38, svoboda: true, levica: true },
  { orderIndex: 39, svoboda: true, levica: true },
  { orderIndex: 40, svoboda: false, levica: false },
  { orderIndex: 41, svoboda: true, levica: true },
  { orderIndex: 42, svoboda: true, levica: true },
  { orderIndex: 43, svoboda: false, levica: false },
  { orderIndex: 44, svoboda: false, levica: false },
  { orderIndex: 45, svoboda: true, levica: true },
  { orderIndex: 46, svoboda: null, levica: false },
  { orderIndex: 47, svoboda: null, levica: false },
  { orderIndex: 48, svoboda: true, levica: true },
  { orderIndex: 49, svoboda: true, levica: true },
  { orderIndex: 50, svoboda: false, levica: false },
  { orderIndex: 51, svoboda: true, levica: true },
  { orderIndex: 52, svoboda: true, levica: null },
  { orderIndex: 53, svoboda: true, levica: true },
  { orderIndex: 54, svoboda: true, levica: true },
  { orderIndex: 55, svoboda: false, levica: false },
  { orderIndex: 56, svoboda: true, levica: true },
  { orderIndex: 57, svoboda: true, levica: true },
  { orderIndex: 58, svoboda: true, levica: true },
  { orderIndex: 59, svoboda: true, levica: true },
  { orderIndex: 60, svoboda: true, levica: true },
  { orderIndex: 61, svoboda: true, levica: true },
  { orderIndex: 62, svoboda: false, levica: false },
  { orderIndex: 63, svoboda: true, levica: true },
  { orderIndex: 64, svoboda: true, levica: true },
  { orderIndex: 65, svoboda: true, levica: true },
  { orderIndex: 66, svoboda: true, levica: true },
  { orderIndex: 67, svoboda: null, levica: false },
  { orderIndex: 68, svoboda: true, levica: true },
  { orderIndex: 69, svoboda: true, levica: true },
  { orderIndex: 70, svoboda: true, levica: true },
  { orderIndex: 71, svoboda: true, levica: true },
  { orderIndex: 72, svoboda: true, levica: true },
  { orderIndex: 73, svoboda: true, levica: true },
  { orderIndex: 74, svoboda: true, levica: true },
  { orderIndex: 75, svoboda: true, levica: true },
  { orderIndex: 76, svoboda: true, levica: true },
  { orderIndex: 77, svoboda: true, levica: true },
  { orderIndex: 78, svoboda: true, levica: true },
  { orderIndex: 79, svoboda: true, levica: true },
  { orderIndex: 80, svoboda: true, levica: true },
  { orderIndex: 81, svoboda: true, levica: true },
  { orderIndex: 82, svoboda: true, levica: true },
  { orderIndex: 83, svoboda: true, levica: true },
  { orderIndex: 84, svoboda: true, levica: true },
  { orderIndex: 85, svoboda: true, levica: true },
  { orderIndex: 86, svoboda: true, levica: true },
  { orderIndex: 87, svoboda: true, levica: true },
  { orderIndex: 88, svoboda: true, levica: true },
  { orderIndex: 89, svoboda: true, levica: true },
  { orderIndex: 90, svoboda: true, levica: true },
  { orderIndex: 91, svoboda: true, levica: true },
  { orderIndex: 92, svoboda: true, levica: true },
  { orderIndex: 93, svoboda: true, levica: true },
  { orderIndex: 94, svoboda: true, levica: true },
  { orderIndex: 95, svoboda: true, levica: true },
  { orderIndex: 96, svoboda: true, levica: true },
  { orderIndex: 97, svoboda: true, levica: true },
  { orderIndex: 98, svoboda: true, levica: true },
  { orderIndex: 99, svoboda: true, levica: true },
  { orderIndex: 100, svoboda: true, levica: true },
  { orderIndex: 101, svoboda: true, levica: true },
  { orderIndex: 102, svoboda: true, levica: true },
  { orderIndex: 103, svoboda: true, levica: true },
  { orderIndex: 104, svoboda: true, levica: true },
  { orderIndex: 105, svoboda: true, levica: true },
  { orderIndex: 106, svoboda: true, levica: true },
  { orderIndex: 107, svoboda: true, levica: null },
  { orderIndex: 108, svoboda: true, levica: true },
  { orderIndex: 109, svoboda: true, levica: true },
  { orderIndex: 110, svoboda: true, levica: true },
  { orderIndex: 111, svoboda: true, levica: true },
  { orderIndex: 112, svoboda: true, levica: true },
  { orderIndex: 113, svoboda: true, levica: true },
  { orderIndex: 114, svoboda: true, levica: true },
  { orderIndex: 115, svoboda: null, levica: null },
  { orderIndex: 116, svoboda: true, levica: true },
  { orderIndex: 117, svoboda: true, levica: true },
  { orderIndex: 118, svoboda: true, levica: true },
  { orderIndex: 119, svoboda: true, levica: true },
  { orderIndex: 120, svoboda: true, levica: true },
  { orderIndex: 121, svoboda: true, levica: true },
  { orderIndex: 122, svoboda: true, levica: true },
  { orderIndex: 123, svoboda: true, levica: true },
  { orderIndex: 124, svoboda: true, levica: true },
  { orderIndex: 125, svoboda: true, levica: true },
  { orderIndex: 126, svoboda: true, levica: true },
  { orderIndex: 127, svoboda: true, levica: null },
  { orderIndex: 128, svoboda: true, levica: true },
  { orderIndex: 129, svoboda: true, levica: true },
  { orderIndex: 130, svoboda: true, levica: true },
  { orderIndex: 131, svoboda: true, levica: true },
  { orderIndex: 132, svoboda: true, levica: true },
  { orderIndex: 133, svoboda: null, levica: true },
  { orderIndex: 134, svoboda: true, levica: true },
  { orderIndex: 135, svoboda: true, levica: true },
  { orderIndex: 136, svoboda: true, levica: true },
  { orderIndex: 137, svoboda: true, levica: true },
  { orderIndex: 138, svoboda: true, levica: true },
  { orderIndex: 139, svoboda: true, levica: true },
  { orderIndex: 140, svoboda: true, levica: true },
  { orderIndex: 141, svoboda: true, levica: true },
  { orderIndex: 142, svoboda: true, levica: true },
  { orderIndex: 143, svoboda: true, levica: true },
  { orderIndex: 144, svoboda: true, levica: true },
  { orderIndex: 145, svoboda: true, levica: true },
  { orderIndex: 146, svoboda: true, levica: true },
  { orderIndex: 147, svoboda: true, levica: true },
  { orderIndex: 148, svoboda: true, levica: true },
  { orderIndex: 149, svoboda: true, levica: true },
  { orderIndex: 150, svoboda: true, levica: true },
  { orderIndex: 151, svoboda: true, levica: false },
  { orderIndex: 152, svoboda: true, levica: false },
  { orderIndex: 153, svoboda: true, levica: true },
  { orderIndex: 154, svoboda: true, levica: true },
  { orderIndex: 155, svoboda: true, levica: true },
  { orderIndex: 156, svoboda: true, levica: true },
  { orderIndex: 157, svoboda: true, levica: null },
  { orderIndex: 158, svoboda: true, levica: true },
  { orderIndex: 159, svoboda: true, levica: true },
  { orderIndex: 160, svoboda: true, levica: false },
  { orderIndex: 161, svoboda: true, levica: true },
  { orderIndex: 162, svoboda: true, levica: true },
  { orderIndex: 163, svoboda: true, levica: true },
  { orderIndex: 164, svoboda: null, levica: true },
  { orderIndex: 165, svoboda: true, levica: true },
  { orderIndex: 166, svoboda: true, levica: true },
  { orderIndex: 167, svoboda: true, levica: true },
  { orderIndex: 168, svoboda: true, levica: true },
  { orderIndex: 169, svoboda: true, levica: true },
  { orderIndex: 170, svoboda: true, levica: true },
  { orderIndex: 171, svoboda: true, levica: true },
  { orderIndex: 172, svoboda: true, levica: true },
  { orderIndex: 173, svoboda: true, levica: true },
  { orderIndex: 174, svoboda: true, levica: true },
  { orderIndex: 175, svoboda: true, levica: true },
  { orderIndex: 176, svoboda: true, levica: true },
  { orderIndex: 177, svoboda: true, levica: true },
  { orderIndex: 178, svoboda: true, levica: true },
  { orderIndex: 179, svoboda: true, levica: true },
];

for (const ov of svobodaLevicaOverrides) {
  stanceMap.svoboda[ov.orderIndex] = ov.svoboda;
  stanceMap["levica-vesna"][ov.orderIndex] = ov.levica;
}

export function getStanceForParty(
  partySlug: string,
  categoryIndex: number,
  questionIndex: number,
  orderIndex?: number
): boolean | null {
  const byOrder = orderIndex !== undefined ? stanceMap[partySlug]?.[orderIndex] : undefined;
  if (byOrder !== undefined) return byOrder ?? null;
  return null;
}

export const nationalSegments = [
  { name: "Zdravstvo", slug: "zdravstvo", icon: "Heart", description: "Kakovostno in dostopno zdravstvo za vse.", orderIndex: 0 },
  { name: "Šolstvo in izobraževanje", slug: "solstvo", icon: "GraduationCap", description: "Moderno izobraževanje za prihodnost.", orderIndex: 1 },
  { name: "Finance države", slug: "finance", icon: "Landmark", description: "Transparentne in trajnostne javne finance.", orderIndex: 2 },
  { name: "Pokojnine in starejši", slug: "pokojnine", icon: "Users", description: "Dostojne pokojnine in oskrba starejših.", orderIndex: 3 },
  { name: "Stanovanjska politika", slug: "stanovanja", icon: "Home", description: "Dostopna stanovanja za vse.", orderIndex: 4 },
  { name: "Transparentnost in nadzor", slug: "transparentnost", icon: "ShieldCheck", description: "Odgovornost in preglednost politikov.", orderIndex: 5 },
  { name: "Digitalizacija države", slug: "digitalizacija", icon: "Monitor", description: "E-uprava in drzava.gov.si.", orderIndex: 6 },
  { name: "Pravosodje", slug: "pravosodje", icon: "Scale", description: "Hitro in neodvisno pravosodje.", orderIndex: 7 },
  { name: "Okolje in energetika", slug: "okolje", icon: "Leaf", description: "Zelena energija in trajnost.", orderIndex: 8 },
  { name: "Infrastruktura in promet", slug: "infrastruktura", icon: "Train", description: "Železnica, javni prevoz, 5G.", orderIndex: 9 },
  { name: "Demografija in mladi", slug: "demografija", icon: "Baby", description: "Podpora družinam in mladim.", orderIndex: 10 },
  { name: "Varnost", slug: "varnost", icon: "Shield", description: "Kibernetska in fizična varnost.", orderIndex: 11 },
  { name: "Gospodarstvo in podjetništvo", slug: "gospodarstvo", icon: "Briefcase", description: "Podpora podjetjem in inovacijam.", orderIndex: 12 },
  { name: "Zunanja politika", slug: "zunanja-politika", icon: "Globe", description: "Vloga v EU in svetu.", orderIndex: 13 },
  { name: "Kultura in šport", slug: "kultura-sport", icon: "Palette", description: "Kultura, šport in dediščina.", orderIndex: 14 },
];

export const nationalNeedsBySegment: Record<string, { title: string; description: string; priority: number }[]> = {
  zdravstvo: [
    { title: "Skrajšanje čakalnih dob", description: "Zakonsko omejene čakalne dobe za diagnosticiranje in zdravljenje.", priority: 1 },
    { title: "Več zdravnikov specialistov", description: "Več štipendij in motivacij za specializacijo.", priority: 1 },
    { title: "Digitalizacija zdravstvenih kartotek", description: "E-karton in zamenljivost podatkov med zavodi.", priority: 2 },
    { title: "Boljše plačilo zdravstvenih delavcev", description: "Konkurenčne plače v javnem zdravstvu.", priority: 1 },
    { title: "Preventivni programi", description: "Sistematični pregledi in preventiva.", priority: 2 },
  ],
  solstvo: [
    { title: "Posodobitev učnih načrtov", description: "Učni načrti, prilagojeni 21. stoletju.", priority: 1 },
    { title: "Več učiteljev, manjši razredi", description: "Manjše razrede za boljšo kakovost.", priority: 1 },
    { title: "Brezplačno izobraževanje na vseh ravneh", description: "Vključno z vrtci in fakultetami.", priority: 1 },
    { title: "Finančna pismenost in programiranje", description: "Obvezna vsebina v osnovni šoli.", priority: 2 },
    { title: "Boljše plačilo učiteljev", description: "Povišanje plač v izobraževanju.", priority: 1 },
  ],
  finance: [
    { title: "Transparenten prikaz proračuna", description: "Javno dostopni podatki o porabi.", priority: 1 },
    { title: "Zmanjšanje javnega dolga", description: "Trajnostna fiskalna politika.", priority: 1 },
    { title: "Učinkovitejša poraba davkoplačevalskega denarja", description: "Optimizacija javne porabe.", priority: 1 },
    { title: "Poenostavitev davčnega sistema", description: "Manj birokracije za davkoplačevalce.", priority: 2 },
  ],
  pokojnine: [
    { title: "Dostojne pokojnine", description: "Povezava z minimalno plačo in življenjskim minimumom.", priority: 1 },
    { title: "Dolgotrajna oskrba", description: "Financiranje dolgotrajne oskrbe.", priority: 1 },
    { title: "Programi za aktivno staranje", description: "Vključevanje starejših v družbo.", priority: 2 },
    { title: "Oskrbovana stanovanja", description: "Stanovanja s pomočjo za starejše.", priority: 2 },
  ],
  stanovanja: [
    { title: "Gradnja javnih najemnih stanovanj", description: "Državna in občinska stanovanja.", priority: 1 },
    { title: "Regulacija kratkoročnih najemov (Airbnb)", description: "Omejitve za turistične najeme.", priority: 2 },
    { title: "Subvencije za mlade kupce", description: "Stanovanjski krediti in subvencije.", priority: 1 },
    { title: "Omejitev cen najemnin", description: "Regulacija trga najemnin.", priority: 2 },
  ],
  transparentnost: [
    { title: "Potrdila o nekaznovanosti za vse politične kandidate", description: "Obvezno pred kandidaturo.", priority: 1 },
    { title: "Obvezno testiranje politikov na droge", description: "Preverjanje za vse nosilce javnih funkcij.", priority: 1 },
    { title: "Prepoved objavljanja anket 30 dni pred volitvami", description: "Preprečevanje manipulacije volivcev.", priority: 1 },
    { title: "Javno dostopne premoženjske kartice", description: "Transparentnost premoženja.", priority: 1 },
    { title: "Strožji nadzor nad lobiranjem", description: "Registri in omejitve.", priority: 2 },
    { title: "Omejitev mandatov", description: "Maksimalno število zaporednih mandatov.", priority: 2 },
  ],
  digitalizacija: [
    { title: "Platforma drzava.gov.si", description: "Centralni portal: finance, zdravstvo, šolstvo, pokojnine – vsak segment z vizualizacijami.", priority: 1 },
    { title: "E-uprava: vsi postopki digitalno", description: "Brez papirja, hitro.", priority: 1 },
    { title: "E-volitve v prihodnosti", description: "Možnost e-glasovanja po preizkušenem sistemu.", priority: 2 },
  ],
  pravosodje: [
    { title: "Hitrejši sodni postopki", description: "Skrajšanje trajanja postopkov.", priority: 1 },
    { title: "Boj proti korupciji", description: "Strožje kazni in preprečevanje.", priority: 1 },
    { title: "Neodvisnost sodstva", description: "Vetev oblasti brez političnega vpliva.", priority: 1 },
  ],
  okolje: [
    { title: "Zeleni prehod", description: "Obnovljivi viri in zmanjšanje emisij.", priority: 1 },
    { title: "Jedrska energija (JEK2)", description: "Drugi blok jedrske elektrarne Krško.", priority: 1 },
    { title: "Obnovljivi viri", description: "Sončna, vetrna, biomasa.", priority: 1 },
    { title: "Krožno gospodarstvo", description: "Ponovna uporaba in recikliranje.", priority: 2 },
  ],
  infrastruktura: [
    { title: "Izboljšanje železniškega omrežja", description: "Hitri vlaki in povezave.", priority: 1 },
    { title: "Javni prevoz", description: "Dostopen in cenovno ugoden.", priority: 1 },
    { title: "Kolesarska infrastruktura", description: "Varna kolesarska omrežja.", priority: 2 },
    { title: "Digitalna infrastruktura (5G, optika)", description: "Hitri internet povsod.", priority: 1 },
  ],
  demografija: [
    { title: "Spodbujanje rodnosti", description: "Dodatki in ugodnosti za družine.", priority: 1 },
    { title: "Ugodnosti za mlade družine", description: "Stanovanjski in otroški dodatki.", priority: 1 },
    { title: "Cenovno dostopna stanovanja za mlade", description: "Programi za prvo stanovanje.", priority: 1 },
    { title: "Preprečevanje bega možganov", description: "Zaposlitve in plače za visoko usposobljene.", priority: 1 },
  ],
  varnost: [
    { title: "Kibernetska varnost", description: "Zaščita državnih in kritičnih sistemov.", priority: 1 },
    { title: "Obramba", description: "2% BDP za obrambo.", priority: 1 },
    { title: "Civilna zaščita", description: "Pripravljenost na nesreče.", priority: 2 },
    { title: "Gasilstvo in reševanje", description: "Oprema in kadri.", priority: 2 },
  ],
  gospodarstvo: [
    { title: "Podpora malim podjetjem", description: "Posojila, svetovanje, davčne olajšave.", priority: 1 },
    { title: "Zmanjšanje birokracije", description: "Enotna okna in digitalni postopki.", priority: 1 },
    { title: "Privabljanje tujih investicij", description: "Ugodnosti za investitorje.", priority: 1 },
    { title: "Inovacije in R&D", description: "Raziskave in razvoj.", priority: 2 },
  ],
  "zunanja-politika": [
    { title: "Aktivna vloga v EU", description: "Sodelovanje v odločanju EU.", priority: 1 },
    { title: "Človekove pravice", description: "Spoštovanje človekovih pravic.", priority: 1 },
    { title: "Razvojna pomoč", description: "Pomoč državam v razvoju.", priority: 2 },
    { title: "Zahodni Balkan", description: "Širitev EU na Balkan.", priority: 1 },
  ],
  "kultura-sport": [
    { title: "Financiranje kulture", description: "Javna podpora kulturi in umetnosti.", priority: 1 },
    { title: "Športna infrastruktura", description: "Dvorane, igrišča, poti.", priority: 1 },
    { title: "Ohranjanje kulturne dediščine", description: "Varstvo spomenikov in tradicije.", priority: 1 },
  ],
};
